services:
  - type: web
    name: notas-backend
    env: python
    plan: free
    region: oregon
    repo: https://github.com/josephvr13/notasBackend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notas-db
          property: connectionString

databases:
  - name: notas-db
    plan: free
    region: oregon
    databaseName: notas_db
    user: notas_user   # nombre de usuario en la BD
    mysqlVersion: 8
